### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by JHSawatzki** [arduino-libraries/Arduino_PortentaMachineControl#13]
All the new files are MPL and the ones taken from the deprecated lib are LGPL. Would be nice to stick to one license used in the whole library.

**Comment by leonardocavagnis** [comment]
Hi @JHSawatzki,
Thanks! I submitted the PR, take a look if sounds good for you!

**Comment by JHSawatzki** [comment]
Looks good! Thanks for the quick response.
