### ISSUE TITLE
Separation of RTD and TC classes confusing

### ISSUE THREAD

**Issue by JHSawatzki** [arduino-libraries/Arduino_PortentaMachineControl#14]
Both probe types use the same inputs/channels so the current implementation is confusing, espacially when using both types in the same project.

I suggest using a shared class like I did in my fork of the old lib, see https://github.com/JHSawatzki/Arduino_MachineControl/blob/master/src/Arduino_MachineControl.h

I could probably also provide a pull request with an implementation not breaking your current API.

**Comment by leonardocavagnis** [comment]
Hi @JHSawatzki,
Thanks for the proposal!
I don't completely agree with your point. We moved to separate classes to avoid using the "double dot" notation (`temp_probes.rtd.`) of the deprecated one. 
However, I invite you to propose your solution in a PR, and I'll analyze it. 😊
