### ISSUE TITLE
Examples for Modbus, WiFi and WebServer

### ISSUE THREAD

**Issue by PatrikRindlisbacher** [arduino-libraries/Arduino_PortentaMachineControl#21]
The examples for the Portenta Machine Control are very brief. 
No Modbus /  Wifi / web server examples. 

The migration took me a lot of time and I haven't solved all the puzzles yet.

**Comment by PatrikRindlisbacher** [comment]
Thank you very much for your reply

As a user, it is difficult to estimate what is for what.
Only two products are mentioned for the web server. and not the machine control
[Portenta H7 (ABX00042)] 
[Portenta H7 Lite Connected (ABX00046)]

It would not be a luxury for the PLC to also provide samples that are used for real PLC control

**Comment by manchoz** [comment]
@PatrikRindlisbacher, take a look also at

- https://github.com/khoih-prog/EthernetWebServer
- https://github.com/khoih-prog/WiFiWebServer

Any example for Portenta H7 will also work for the PMC (it is literally a Portenta H7 with a carrier add-on).
