### ISSUE TITLE
PT1000 temperature probes not supported?

### ISSUE THREAD

**Issue by toqduj** [arduino-libraries/Arduino_PortentaMachineControl#24]
Despite the claims in the PMC datasheet, I can't see how the PT1000 temperature probes could be supported here. 

The hardware seems to top out at a maximum resistance of 400 Ohms, and I can't find any examples on the internet either of how this is supposed to work (the suggested change of RNOMINAL to 1000.0 does not affect the hardware). 

Is there a chip flag that should be set for these?

**Comment by leonardocavagnis** [comment]
Hi @toqduj,
The PT1000 is not compatible. The [official documentation](https://docs.arduino.cc/resources/datasheets/AKX00032-datasheet.pdf) was updated in 2022 to reflect this and remove it.
<img width="684" alt="Screenshot 2024-12-06 alle 10 05 00" src="https://github.com/user-attachments/assets/652da941-9fdf-4e49-98b8-22dff5237bd2">

**Comment by toqduj** [comment]
ah ok, that's too bad. thanks very much for the clarification!
