### ISSUE TITLE
DigitalOutputs writeAll function not correctly writing to each Output

### ISSUE THREAD

**Issue by kevmk04** [arduino-libraries/Arduino_PortentaMachineControl#8]
When using the writeAll function for Digital Outputs, the function will only turn on/off all Outputs regardless of input integer.  For example, supplying any value greater than zero will turn ON all Outputs.  Providing a zero will turn OFF all Outputs. 

Function source code is here: 
https://github.com/arduino-libraries/Arduino_PortentaMachineControl/blob/563b200eaa543dc40b58fcdb2a4f760877f40f1d/src/DigitalOutputsClass.cpp#L78

Within the function, it appears that the logical (&&) operator is being used where a bitwise (&) should be.  I was able to test this with a Portenta Machine Control and confirmed that switching the operator fixes the issue and allows the integer to be correctly parsed into the individual outputs.  

Line w/ Operator:
https://github.com/arduino-libraries/Arduino_PortentaMachineControl/blob/563b200eaa543dc40b58fcdb2a4f760877f40f1d/src/DigitalOutputsClass.cpp#L80

**Comment by kevmk04** [comment]
I'm happy to create a PR for this fix if desired.

**Comment by leonardocavagnis** [comment]
Dear @kevmk04,
We're waiting for the PR 😉

**Comment by kevmk04** [comment]
Sorry for the delay, missed the notifications.  PR is up for your review!
